name: github_models
description: A Dart package for interacting with GitHub Models API
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  # Add dependencies here

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0