name: github_models
description: A Dart package for interacting with GitHub Models API
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0