name: github_models
description: A Dart package for interacting with GitHub Models API
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  freezed: ^3.0.0
  json_serializable: ^6.0.0
  lints: ^4.0.0
  test: ^1.0.0
