name: Dart CI

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.7.0'
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Verify formatting
      run: dart format --set-exit-if-changed .
    
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
    
    - name: Verify generated files are up to date
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Generated files are not up to date. Please run 'dart run build_runner build --delete-conflicting-outputs' and commit the changes."
          git status --porcelain
          exit 1
        fi
    
    - name: Analyze project source
      run: dart analyze
    
    - name: Run tests
      run: dart test



